#!/bin/sh

root=$(realpath $(dirname $0)/..)

uri="https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json"
output_path="$root/priv/kubernetes-openapi-specification.json"

curl -sS -o $output_path $uri
